name: Sync Google Doc to README

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 mins
  workflow_dispatch:        # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install pypandoc requests

      - name: Sync README from Google Docs
        env:
          GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}
        run: python sync_gdoc.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-sync README from Google Docs" || echo "No changes"
          git push
